// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID        int32
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Invoice struct {
	ID            int32
	InvoiceNumber string
	InvoiceDate   time.Time
	CustomerID    int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type InvoiceItem struct {
	ID        int32
	InvoiceID int32
	ProductID int32
	Count     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Product struct {
	ID             int32
	Name           string
	Description    sql.NullString
	Price          string
	AvailableItems int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
